version: '3.7'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment: 
      PORT: 3000
    ports:
    - 3000:3000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
    - 1234:1234
    depends_on:
      - server
