name: Build

on: [push, pr]

jobs:
  client-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
        working-directory: client/
        run: |
          npm install
          npm run lint
