name: Build

on: [push, pull_request]

jobs:
  client-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: eslint
        working-directory: client/
        run: |
          npm install
          npm run lint

  server-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: eslint
        working-directory: server/
        run: |
          npm install
          npm run lint
